// Generated from Rust by `pnpm bindings`. DO NOT EDIT.
// This file has been generated by Specta. Do not edit this file manually.
/**  Basic information about the running app. */
export type AppInfo = {
	name: string,
	version: string,
};

export type CollectionNode = {
	id: string,
	parentId: string | null,
	name: string,
	sortOrder: number,
};

/**  All folders and requests; the UI builds the tree from `parentId` / `collectionId`. */
export type CollectionTree = {
	collections: CollectionNode[],
	requests: SavedRequest[],
};

/**  Connection state of one server. */
export type ConnectionState = "disconnected" | "connecting" | "connected" | "error";

/**  Direction of a message relative to the party that owns the transport. */
export type Direction = 
/**  Sent by us to the peer. */
"out" | 
/**  Received from the peer. */
"in";

export type Environment = {
	id: string,
} & EnvironmentInput;

export type EnvironmentInput = {
	name: string,
	/**  Values are plain text or `keyring:` references. */
	variables: { [key in string]: string },
};

export type HistoryEntry = {
	id: number,
	serverId: string,
	method: string,
	target: string,
	arguments: unknown,
	isError: boolean,
	cancelled: boolean,
	durationMs: number | null,
	result: unknown | null,
	error: string | null,
	ts: number,
};

export type HistoryFilter = {
	serverId?: string | null,
	/**  Case-insensitive match on the target, the arguments, and the error text. */
	search?: string | null,
	/**  Page backwards: only entries older than this id. */
	beforeId?: number,
	/**  Default 100, maximum 1000. Newest first. */
	limit?: number | null,
};

/**  Result of importing a collection file. */
export type ImportReport = {
	/**  Id of the imported top-level folder. */
	collectionId: string,
	collectionsCreated: number,
	requestsCreated: number,
	/**  Requests that could not be imported, with the reason (e.g. unknown server). */
	skipped: string[],
};

/**  `mcp://list-changed`: the server sent `notifications/*\/list_changed`. */
export type ListChangedEvent = {
	serverId: string,
	kind: ListKind,
};

/**  Which list of a server changed. */
export type ListKind = "tools" | "resources" | "prompts";

/**  `mcp://log` */
export type LogEvent = {
	serverId: string,
	source: LogSource,
	/**  `debug` | `info` | `warning` | `error` (MCP levels are mapped onto these). */
	level: string,
	line: string,
	ts: number,
};

/**  Where a log line came from. */
export type LogSource = 
/**  The server's stderr (stdio servers). */
"stderr" | 
/**  An MCP `notifications/message` log notification. */
"server" | 
/**  MCP Studio itself (spawn, reconnect, ...). */
"studio";

/**  Filters for [`query_messages`]. All fields are optional and combined with AND. */
export type MessageFilter = {
	sessionId?: string | null,
	serverId?: string | null,
	/**  Only messages with a larger id (used to catch up after a live subscription started). */
	afterId?: number,
	/**  Only messages with a smaller id (paging backwards). */
	beforeId?: number,
	/**  Exact JSON-RPC method, e.g. `tools/call`. Responses match through their request. */
	method?: string | null,
	direction?: Direction | null,
	errorsOnly?: boolean,
	/**  Case-insensitive text search over the raw payload. */
	search?: string | null,
	/**
	 *  Maximum number of rows (default 500, max 5000). The newest matching rows are returned,
	 *  oldest first.
	 */
	limit?: number | null,
};

/**  A recorded JSON-RPC message as stored, sent to the UI live and returned by queries. */
export type MessageRecord = {
	id: number,
	sessionId: string,
	serverId: string,
	direction: Direction,
	jsonrpcId: string | null,
	method: string | null,
	/**  The JSON-RPC message as text. */
	payload: string,
	bytes: number,
	isError: boolean,
	/**  Unix milliseconds. */
	ts: number,
	/**  For responses: milliseconds since the matching request (filled by queries). */
	durationMs: number | null,
};

/**  `mcp://progress`: progress of a running tool call. */
export type ProgressEvent = {
	serverId: string,
	callId: string,
	progress: number | null,
	total: number | null,
	message: string | null,
};

export type PromptArgumentInfo = {
	name: string,
	description?: string | null,
	required?: boolean,
};

export type PromptInfo = {
	name: string,
	title?: string | null,
	description?: string | null,
	arguments?: PromptArgumentInfo[],
};

/**  What the UI needs to help the user configure a client. */
export type ProxyInfo = {
	/**  Loopback port the stdio proxy program connects to. */
	controlPort: number,
	/**  Absolute path of the `mcp-studio-proxy` program, if it was found. */
	proxyBinary: string | null,
	discoveryFile: string,
};

export type ResourceInfo = {
	uri: string,
	name: string,
	title?: string | null,
	description?: string | null,
	mimeType?: string | null,
};

export type ResourceTemplateInfo = {
	uriTemplate: string,
	name: string,
	title?: string | null,
	description?: string | null,
	mimeType?: string | null,
};

export type SavedRequest = {
	id: string,
	sortOrder: number,
	updatedAt: number,
} & SavedRequestInput;

/**  What the user edits about a saved request. */
export type SavedRequestInput = {
	collectionId: string,
	serverId: string,
	/**  MCP method, e.g. `tools/call`. */
	method: string,
	name: string,
	toolName: string | null,
	arguments: unknown,
	notes: string,
};

/**  A stored server definition. */
export type ServerDefinition = {
	id: string,
	/**  Unix milliseconds. Exported to TypeScript as `number` (specta forbids `i64`). */
	createdAt: number,
	updatedAt: number,
} & ServerInput;

/**  What the server told us during `initialize`. */
export type ServerDetails = {
	protocolVersion: string,
	name: string,
	version: string,
	instructions: string | null,
	capabilities: unknown,
	hasTools: boolean,
	hasResources: boolean,
	hasPrompts: boolean,
};

/**  What the user edits: everything except identity and timestamps. */
export type ServerInput = {
	name: string,
	transport: TransportKind,
	command: string | null,
	args: string[],
	env: { [key in string]: string },
	cwd: string | null,
	url: string | null,
	headers: { [key in string]: string },
	tags: string[],
};

/**  `mcp://status` */
export type StatusEvent = {
	serverId: string,
	sessionId: string | null,
	state: ConnectionState,
	message: string | null,
};

/**  A tool call to run. */
export type ToolCallRequest = {
	serverId: string,
	toolName: string,
	/**  Arguments; `{{variables}}` are resolved from the environment. */
	arguments: unknown,
	environmentId: string | null,
	/**  Chosen by the caller; identifies the call for progress events and cancellation. */
	callId: string,
};

/**  The outcome of a tool call. */
export type ToolCallResult = {
	callId: string,
	/**  The MCP `CallToolResult` (content, structuredContent, isError, ...). Null if cancelled. */
	result: unknown,
	/**  The tool reported an error (`isError`). */
	isError: boolean,
	cancelled: boolean,
	durationMs: number,
};

export type ToolInfo = {
	name: string,
	title?: string | null,
	description?: string | null,
	/**  JSON Schema of the arguments. */
	inputSchema?: unknown,
	outputSchema?: unknown | null,
	annotations?: unknown | null,
};

/**  How a server is reached. */
export type TransportKind = "stdio" | "http";
